export const UserRole: any = {
  GUEST_USER : 'GUEST_USER',
  CURRICULUM_SELLER : 'CURRICULUM_SELLER',
  STUDENT : 'STUDENT',
  ADMIN : 'ADMIN',
  DIRECTORY_MEMBER : 'DIRECTORY_MEMBER',
  CERTIFICATION_MANAGER : 'CERTIFICATION_MANAGER',
  INSTRUCTOR_ADMIN : 'INSTRUCTOR_ADMIN',
  CURRICULUM_ADMIN : 'CURRICULUM_ADMIN',
  COURSE_CREATOR_ADMIN : 'COURSE_CREATOR_ADMIN',
  BOOKING_PROFESSIONAL : 'BOOKING_PROFESSIONAL',
  BOOKING_USER : 'BOOKING_USER'
}


export const USER_ROLES = {
  GUEST_USER : 'GUEST_USER',
  CURRICULUM_SELLER : 'CURRICULUM_SELLER',
  STUDENT : 'STUDENT',
  ADMIN : 'ADMIN',
  DIRECTORY_MEMBER : 'DIRECTORY_MEMBER',
  CERTIFICATION_MANAGER : 'CERTIFICATION_MANAGER',
  INSTRUCTOR_ADMIN : 'INSTRUCTOR_ADMIN',
  CURRICULUM_ADMIN : 'CURRICULUM_ADMIN',
  COURSE_CREATOR_ADMIN : 'COURSE_CREATOR_ADMIN',
  BOOKING_PROFESSIONAL : 'BOOKING_PROFESSIONAL',
  BOOKING_USER : 'BOOKING_USER'
}
